add main service
Daniil-Horobets/java-explore-with-me pull request #2
Opened 2023-02-24 17:07 UTC by Daniil-Gorobets

Добавлен основной сервис приложения

2023-02-25 16:41 UTC, Fleaman777 requested changes

2023-02-25 16:41 UTC, Fleaman777 commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/dto/CategoryDto.java
> +    String name;
поля должны быть private

2023-02-25 16:41 UTC, Fleaman777 commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/dto/NewCategoryDto.java
> +    String name;
и тут тоже private 

как и в др похожих местах

2023-02-25 16:41 UTC, Fleaman777 commented on ewm-main-service/src/main/java/ru/practicum/ewm/compilation/utils/CompilationConverter.java
> +                .collect(Collectors.toList());
не самая читаемая конструкция, когда в метод в качестве аргумента передаешь стрим, 
лучше его результат вынести в локальную переменную, с пододящем назнванием, 
что упорстит восприятие кода

2023-02-25 16:41 UTC, Fleaman777 commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/controller/AdminEventController.java
> +            @RequestParam(defaultValue = "10") @Positive Integer size) {
понимаю, что это было требование ТЗ,
но так, заметка на будущее, лучше конечно стараться не делать очень много параметров в запросе, а тем более списков, т.к. большое количество параметров ухудшает построение взаимодействия между сервисами
как альтерантива, использовать боди в пост запросе

2023-02-25 16:41 UTC, Fleaman777 commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/AdminEventService.java
> +    @Autowired
можно не проставлять аннотацию @Autowired, если поля написаны с модификатором final и используется аннотация @RequiredArgsConstructor

при выполнение этих 2х условий, спринг компоненты автовайрятся сами под капотом

применимо ко всем похожим местам

2023-02-25 16:41 UTC, Fleaman777 commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/PrivateEventService.java
> +        log.info("|||||||||||||||||||||||||||||||||||||||||||||||||||||||");
не самый информативный лог )

2023-02-25 16:41 UTC, Fleaman777 commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/util/EventConverter.java
> +                                .collect(Collectors.toList()))
этот стрим хорошо было бы вынести в приватный метод, что бы читалось удобней

2023-02-25 16:41 UTC, Fleaman777 commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/util/EventConverter.java
> +                    ));
и эти стримы (точнее логику внутри методов .map, .collect) хорошо было бы немного разбить, 

стримы хорошо воспринимаются, когда они не перегружены логикой внутри, а если даже и есть какая-нибудь специфическая логика фильтрации или преобразования, то ее просто можно вынести в отдельный метод, 
в таком случае читая стрим, по названию методов которые будут использоваться внутри , будет понятно, что делается на каждом этапе стрима, если захочится глубже понять, что именно происходит, то тогда можно будет просто перейти во вспомогательный метод и разобраться


применимо ко всем аналогичным местам

2023-02-25 16:41 UTC, Fleaman777 commented on ewm-main-service/src/main/java/ru/practicum/ewm/request/service/PrivateRequestService.java
> +    }
получился достаточно длинный метод, с множеством if else условий, что затрудняет восприятие,
попробуй часть логики вынести в приватные методы, тем самым уменьшишь длину и повысишь читаемость

2023-02-25 16:41 UTC, Fleaman777 commented on ewm-main-service/src/main/java/ru/practicum/ewm/util/stats/AppNames.java
> +public final class AppNames {
добавив в название классе Constants,
можно будет не заходить во внутрь класса, что бы понять, какой именно функционал в нем находится

2023-02-25 19:11 UTC, Daniil-Gorobets commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/dto/CategoryDto.java
> +    String name;
Поля private, так как класс аннотирован `@FieldDefaults(level = AccessLevel.PRIVATE)`. Ревьюер, проверявший первую часть проекта, указал на то, что желательно использовать эту аннотацию вместо многочисленного повторения модификатора доступа.

2023-02-25 19:11 UTC, Daniil-Gorobets commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/dto/NewCategoryDto.java
> +    String name;
и тут тоже аннотация `@FieldDefaults(level = AccessLevel.PRIVATE)`

как и в др похожих местах))

2023-02-26 16:28 UTC, Fleaman777 commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/dto/CategoryDto.java
> +    String name;
воу, век живи, век учись,
тогда замечание снимается. возьму на воорудение)

2023-02-26 16:30 UTC, Fleaman777 approved these changes

2023-02-26 16:54 UTC, merged